### PR TITLE
Bender integration

### PR DESCRIPTION
**Pull request by micprog**
Integrated bender, as in #55 

Fixed peripherals according to #58, all tests in the CI now pass

### CODE REVIEW

**Comment by luca-valente** [comment]
Looks good to me! @OttG 
Thanks! @micprog

**Comment by OttG** [comment]
I'm finding it difficult to resolve the conflicts, did you rebase the changes on the master after the revert?

**Comment by micprog** [comment]
> I'm finding it difficult to resolve the conflicts, did you rebase the changes on the master after the revert?

No, I haven't rebased, I simply continued the branch, but I will attempt to rebase and push to see if that works.

**Comment by micprog** [comment]
Due to the merged branch and subsequent reverted commit, prior changes were already included and through the revert git did not want these changes anymore. I fixed this by reverting the revert and added the changes on top, which should now work. Let me know if there are any further issues.

**Comment by OttG** [comment]
Now it looks ok, before it showed only 4 files changed but now are 27. I will wait for the CI to finish to be safe.

**Comment by OttG** [comment]
Ok everything passed

**Pull request merged**
